config:
  folders:
    - cmds
    - events
    - games
user_id:
  - &bot_owner 384233645621248011
  - &Juxta 546614210243854337
  - &Traveler 590430031281651722
emojis:
  check: &yes \N{WHITE HEAVY CHECK MARK}
  cancel: &no \N{CROSS MARK}
channel:
  error_log: &error_record 812628283631206431
  command_log: 747054636778913853
servers:
  - &test_server 719132687897591808
  - &furry_server 669934356172636199
subscribe:
  overview_msg: 807883465755197472
  log_channel: 740196718477312061
  error_log: *error_record
  vaild_category:
    - 719132688392519720
    - 696655511197712414
  exclude_channel:
    - &overview_channel 675956755112394753
  manager:
    - *bot_owner
    - *Juxta
  check:
    check: *yes
    cancel: *no
game:
  an-jia:
    bzz:
    - <:bzz04:811230937273729065>
    - <:bzz03:811230936934907936>
    - <:bzz02:811230937224183818>
    - <:bzz01:811230937000968204>
    coin:
    - <:coin02:811230937274122250>
    - <:coin01:811230937106481173>
event:
  emm:
    https://i.imgur.com/O2KEANT.png: 1
    https://i.imgur.com/pBtSQY2.png: 5
    https://i.imgur.com/qnG94J9.gifv: 3
    https://i.imgur.com/rMfjBLQ.gifv: 4
    https://i.imgur.com/R03kmWs.gifv: 4
  monkey:
    https://i.imgur.com/0AKZQEe.jpg: 2
    "\u54EA\u4F86\u7684\u7334\u5B50": 2
  it's_not:
    https://i.imgur.com/LSg9JN5.jpg: 1
    https://i.imgur.com/cWOYOCA.jpg: 1
    https://i.imgur.com/wPlIu0B.jpg: 1
  pie:
    http://imgur.com/a/RTPG1JW.jpg: 1
    https://i.imgur.com/VExHu1r.png: 1
  pray:
    <:021:685800580958126081>: 1
    <:02:839488926296440863>: 1
    <:034:835896289970880552>: 1
    <:3_:839186971678867507>: 1
    <a:GIF009:752531101276176425>: 1
  programming:
    https://i.imgur.com/H3PvVSN.jpg: 1
    https://i.imgur.com/JZWGnFU.jpg: 1
    https://i.imgur.com/V7RwtXP.jpg: 1
    https://i.imgur.com/tzn1gLp.jpg: 1
    https://i.imgur.com/v0IvaxD.jpg: 1
    https://i.imgur.com/wXakvWk.jpg: 1
  rrr:
    https://i.imgur.com/4qsOH6l.gifv: 1
    https://i.imgur.com/OZVk4wD.gifv: 1
    https://i.imgur.com/edFVqHE.jpg: 1
    https://media.discordapp.net/attachments/719132688392519725/836659641014157332/shake.gif: 1
  what:
    https://i.imgur.com/I33cPpW.jpg: 1
    https://i.imgur.com/WP3KUHc.png: 1
    https://i.imgur.com/Wt9X5M2.jpg: 1
    https://i.imgur.com/spa6UWQ.gifv: 1
    https://i.imgur.com/wMEwGzA.png: 1
  yeah:
    http://imgur.com/a/wEQQkDE.jpg: 1
